brasileirao = ('Flamengo', 'Cruzeiro', 'Palmeiras', 'Mirassol', 'Botafogo', 'Bahia', 'São Paulo', 'Fluminense', 'Bragantino', 'Grêmio', 'Vasco Da Gama', 'Corinthians', 'Ceará SC', 'Atlético - MG', 'Internacional', 'Santos', 'Juventude', 'EC Vitória', 'Fortaleza', 'Sport Recife')
print('\n--- \033[1;33mTABELA DO BRASILEIRÃO ATUALIZADA\033[m ---')
print('-- \033[1;32mG4\033[m --')
print('\033[1;37m==\033[m' * 20)
print(brasileirao[0])
print(brasileirao[1])
print(brasileirao[2])
print(brasileirao[3])
print(brasileirao[4])

print('\n -- \033[1;34mÚLTIMOS COLOCADOS\33[m --')
print(brasileirao[16])
print(brasileirao[17])
print(brasileirao[18])
print(brasileirao[19])

print('\n -- \033[1;37mORDEM ALFABÉTICA\033[m')
lista_ordenada = sorted(brasileirao)
print(lista_ordenada)